---
dependencies:
  - role: adduser
    user: "{{ addusers.etcd }}"
    when: not ansible_os_family in ['CoreOS', 'Container Linux by CoreOS']
  - role: download
    file: "{{ downloads.etcd }}"
    tags: download

# NOTE: Dynamic task dependency on Vault Role if cert_management == "vault"
