---
addusers:
  etcd:
    name: "{{ etcd_user }}"
    comment: "Etcd user"
    createhome: >-
      {% if ansible_os_family == "CoreOS" %}no{% else %}yes{% endif %}
    home: "/var/lib/etcd"
    system: yes
    shell: /usr/sbin/nologin
    group: "{{ etcd_group }}"
    groups: "{{ etcd_cert_group }}"
    type: >-
      {% if ansible_os_family == "CoreOS" %}cloud-init{% endif %}
  kube:
    name: "{{ kubelet_user }}"
    comment: "Kubernetes user"
    shell: /usr/sbin/nologin
    system: yes
    group: "{{ kubelet_group }}"
    groups: "{{ etcd_cert_group }},{{ kube_cert_group }}"
    createhome: no
  netplug:
    name: "{{ netplug_user }}"
    comment: "Network plugin user"
    createhome: no
    system: yes
    shell: /usr/sbin/nologin
    group: "{{ netplug_group }}"
    groups: "{{ etcd_cert_group }}"

adduser:
  name: "{{ user.name }}"
  group: "{{ user.name|default(None) }}"
  groups: "{{ user.groups|default(None) }}"
  comment: "{{ user.comment|default(None) }}"
  shell: "{{ user.shell|default(None) }}"
  system: "{{ user.system|default(None) }}"
  createhome: "{{ user.createhome|default(None) }}"
  type: "{{ user.type|default(None) }}"
