---
- name: Preinstall | get kube user ID
  shell: /usr/bin/id -u {{ kubelet_user }} || echo 0
  register: kube_uid

- name: Preinstall | get kube group ID
  shell: /usr/bin/id -g {{ kubelet_group }} || echo 0
  register: kube_gid

- name: Preinstall | get kube cert group ID
  shell: /usr/bin/id -g {{ kube_cert_group }} || echo 0
  register: kube_cert_gid

- name: Preinstall | get etcd cert group ID
  shell: /usr/bin/id -g {{ etcd_cert_group }} || echo 0
  register: etcd_cert_gid

- name: Preinstall | get netplug user ID
  shell: /usr/bin/id -u {{ netplug_user }} || echo 0
  register: netplug_uid

- name: Preinstall | get netplug group ID
  shell: /usr/bin/getent group {{ netplug_group }} | cut -d':' -f3 || echo 0
  register: netplug_gid

- set_fact:
    kubelet_user_id: "{{ kube_uid.stdout }}"
    kubelet_group_id: "{{ kube_gid.stdout }}"
    kube_cert_group_id: "{{ kube_cert_gid.stdout }}"
    etcd_cert_group_id: "{{ etcd_cert_gid.stdout }}"
    netplug_user_id: "{{ netplug_uid.stdout }}"
    netplug_group_id: "{{ netplug_gid.stdout }}"
