---
- name: Master | get kube user ID
  shell: /usr/bin/id -u {{ kubelet_user }} || echo 0
  register: kube_uid

- name: Master | get kube group ID
  shell: /usr/bin/getent group {{ kubelet_group }} | cut -d':' -f3 || echo 0
  register: kube_gid

- name: Master | get kube cert group ID
  shell: /usr/bin/getent group {{ kube_cert_group }} | cut -d':' -f3 || echo 0
  register: kube_cert_gid

- name: Master | get etcd cert group ID
  shell: /usr/bin/getent group {{ etcd_cert_group }} | cut -d':' -f3 || echo 0
  register: etcd_cert_gid

- set_fact:
    kubelet_user_id: "{{ kube_uid.stdout }}"
    kubelet_group_id: "{{ kube_gid.stdout }}"
    kube_cert_group_id: "{{ kube_cert_gid.stdout }}"
    etcd_cert_group_id: "{{ etcd_cert_gid.stdout }}"
